server:
  port: ${PORT:8001}
spring:
  application:
    name: config
  profiles:
    active:
    - native
  cloud:
    config:
      allow-override: true
      override-none: true
      server:
        native:
          search-locations:
          - classpath:config
          - classpath:config/{application}/
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
error:
  handling:
    http-status-in-json-response: true
    add-path-to-error: true
    exception-logging: with-stacktrace
