feign:
  client:
    config:
      article-service:
        loggerLevel: full
logging:
  level:
    '[caceresenzo.hello.graphql.api.article.ArticleService]': DEBUG
server:
  port: ${PORT:8006}
spring:
  application:
    name: graphql
  config:
    import: configserver:http://config
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
  graphql:
    graphiql:
      enabled: true
  zipkin:
    base-url: http://zipkin
eureka:
  client:
    enabled: true
    service-url:
      default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka
graphiql:
  cdn:
    enabled: true