server:
  port: ${PORT:8005}
spring:
  application:
    name: post-service
  config:
    import: configserver:http://config
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
  datasource:
    url: jdbc:mysql://localhost:3306/post-service?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: true
    service-url:
      default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka
