server:
  port: ${PORT:8000}
spring:
  application:
    name: gateway
  config:
    import: configserver:http://config
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
  main:
    web-application-type: reactive
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
    register-with-eureka: false
    registry-fetch-interval-seconds: 1
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
