server:
  port: ${PORT:8000}
spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
  main:
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 1
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
