server:
  port: ${PORT:8009}
spring:
  application:
    name: api-key-service
#  config:
#    import: configserver:http://config
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
  data:
    mongodb:
      uuid-representation: standard
      authentication-database: admin
      database: api-key-service
      username: root
      password: password
eureka:
  client:
    enabled: true
    service-url:
      default-zone: ${DISCOVERY_URL:http://localhost:8761}/eureka
