server:
  port: ${PORT:8003}
spring:
  application:
    name: user-service
  config:
    import: configserver:http://config
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
