apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: config:0.0.1-SNAPSHOT
        env:
        - name: DISCOVERY_URL
          value: http://eureka:8761
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8001
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  type: NodePort
  selector:
    app: config
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
#    nodePort: 31000
