apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
  labels:
    app: index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: index:0.0.1-SNAPSHOT
        env:
        - name: PORT
          value: "80"
        - name: CONSUL_HOST
          value: consul-server.consul
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: index
spec:
  type: NodePort
  selector:
    app: index
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: index
#spec:
#  selector:
#    app: index
#  ports:
#    - port: 80
#      targetPort: 80
#  type: LoadBalancer
#  