management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
error:
  handling:
    add-path-to-error: true
    exception-logging: with-stacktrace
    full-stacktrace-http-statuses:
    - 5xx
spring:
  data:
    mongodb:
      host: mongo
      uuid-representation: standard
      authentication-database: admin
      username: root
      password: password
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  sleuth:
    web:
      servlet:
        enabled: true
springdoc:
  disable-i18n: true
  api-docs:
    path: /spec.json
  swagger-ui:
    use-root-path: true