server:
  port: ${PORT:8002}
spring:
  application:
    name: index
  config:
    import: configserver:http://config
  cloud:
    discovery:
      enabled: true
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config
info:
  application:
    name: ${spring.application.name}
    maintainer: Enzo
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
